Repository mesaugat/tech-companies-in-nepal, pull requests merged in 2022-01, with the labels that each got.

#122 Add LinkBinary
  README.md
Labels: new

#123 Add Cloudy Fox Technology Pvt. Ltd.
  README.md
Labels: new

#124 Add Clusus Information Solutions Pvt. Ltd., BlackBox Technologies Pvt. Ltd. & Impetus Incorporation Pvt. Ltd. and remove Segonatech
  README.md
Labels: new, remove

#125 Add a few more companies in operation and remove companies that no longer have a working website
  README.md
Labels: new, remove

#126 Remove Avionte Solutions & Add Chhito Connect Pvt. Ltd.
  README.md
Labels: new, remove

#127 Add Swift Technology
  README.md
Labels: new

#128 Update Bajra Technologies
  README.md
Labels: edit

#129 Add Aspark Systems
  README.md
Labels: new
