Repository mesaugat/tech-companies-in-nepal, pull requests merged in 2023-10, with the labels that each got.

#160 Add "The Next Coders"
  README.md
Labels: new

#159 Correct redirects
  README.md
Labels: enhancement

#161 Update information about UXCam
  README.md
Labels: edit

#163 Add more tech companies in Nepal
  README.md
Labels: new
