Repository mesaugat/tech-companies-in-nepal, pull requests merged in 2024-05, with the labels that each got.

#193 Update Parewa Labs Pvt. Ltd.
  README.md
Labels: edit

#194 Remove Enliv Technology
  README.md
Labels: remove

#189 Added Elytra Solutions
  README.md
Labels: new

#186 Adding AITC International to the tech company list
  README.md
Labels: new

#195 Add Blanxer Technologies Pvt. Ltd.
  README.md
Labels: new

#192 Add Nepal Digital Systems
  README.md
Labels: new
